name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Environment
        uses: krobus00/websocket-service/.github/workflows/presetup.yml@master

      - name: Build app
        run: go build .
