name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: krobus00/websocket-service/.github/workflows/presetup.yml@master

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the application
      run: go build -o myapp
