name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pre-setup
      uses: krobus00/websocket-service/.github/workflows/build-template.yml@master

    - name: Build the application
      run: go build .
